# Generated by Django 5.1.1 on 2025-02-13 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': '1 - Sklad Kategoriyasi',
            },
        ),
        migrations.CreateModel(
            name='FinishCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': '2 - Sklad Kategoriasi',
            },
        ),
        migrations.CreateModel(
            name='FinishProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soni', models.IntegerField()),
                ('narxi', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('nomi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.finishcategory')),
            ],
            options={
                'verbose_name_plural': 'Sklad 2',
            },
        ),
        migrations.CreateModel(
            name='FinishProductHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soni', models.IntegerField()),
                ('status', models.CharField(choices=[('chiqdi', 'Chiqdi'), ('qabul', 'Qabul')], default='chiqdi', max_length=100, verbose_name='Holat')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Sana')),
                ('narxi', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('nomi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.finishcategory')),
            ],
            options={
                'verbose_name_plural': '2 - Sklad',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soni', models.IntegerField()),
                ('narxi', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('nomi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='apps.category')),
            ],
            options={
                'verbose_name_plural': 'Sklad 1',
            },
        ),
        migrations.CreateModel(
            name='ProductHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soni', models.IntegerField()),
                ('status', models.CharField(choices=[('chiqdi', 'Chiqdi'), ('qabul', 'Qabul')], default='chiqdi', max_length=100, verbose_name='Holat')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Sana')),
                ('narxi', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('nomi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.category')),
            ],
            options={
                'verbose_name_plural': '1 - Sklad',
            },
        ),
    ]
